<div class="app_standard center_screen" style="background:linear-gradient(#f2f2f2, #ffffff)">
    <div class="text-center app_jumbotron"><!--MobiShop--></div>
    <div style="width:90%; margin:0px auto">
        <div class="row">
            <div class="about_label" style="margin-top: 15px">Giới thiệu web</div>
            <div class="col-md-7">
                <div style="margin-left: 30px">
                    <h3>Chào mừng bạn đến MobiShop.</h3>

                    <p>
                        Bạn có thể tìm cho mình chiếc điện thoại ưng ý ở đây,
                        từ dòng phổ thông của các hãng như <b>Nokia, Samsung</b>
                        cho đến các dòng sang trọng của các hãng như <b>Vertu</b>.
                    </p>

                    <p>
                        <b>MobiShop</b> là đồ án cuối kỳ môn Lập trình Web 1 của nhóm <b>110001PN</b>.
                    </p>

                    <p>
                        Mọi thắc mắc hay tư vấn có thể liên hệ đường dây "hơi nóng"<br/>
                        <b>SĐT:</b> 0123 445 2107 - gặp người bắt máy<br/>
                        <b>Email:</b> tvquy@fit.hcmus.edu.vn<br/>
                    </p>
                </div>
            </div>
            <div class="col-md-5">
                <img src="../img/mobishop.png" style="margin-top: 15px" alt="MobiShop"/>
            </div>
        </div>

        <div class="row">
            <div class="about_label">Công nghệ nổi bật</div>
            <div class="app_space_line"></div>
            <div class="row">
                <div class="col-md-3">
                    <img src="../img/Technologies/jquery-logo.png" alt="jQuery" width="200px"/>
                </div>
                <div class="col-md-9">
                    <label style="font-size: 20px">jQuery</label>

                    <p>
                        jQuery là một thư viện dạng cross-platform được phát triển từ ngôn ngữ Javascript được thiết kế
                        nhằm đơn giản hóa việc lập trình JavaScript phía Client-side.
                        Được phát hành vào tháng 1 năm 2006 tại BarCamp NYC bởi John Resig và phát triển bởi jQuery
                        Team.
                    </p>
                    Website: <a href="http://jquery.com" target="_blank">jquery.com</a>
                </div>
            </div>

            <div class="app_footer_line"></div>
            <div class="row">
                <div class="col-md-3">
                    <img src="../img/Technologies/ajax-logo.jpg" alt="Ajax" width="210px" />
                </div>
                <div class="col-md-9">
                    <label style="font-size: 20px">Ajax</label>

                    <p>
                        Ajax (Asynchronous JavaScript and XML) là một nhóm các công nghệ phát triển web phía Client-side để tạo ứng dụng web bất đồng bộ.
                        Với Ajax, ứng dụng web có thể gởi và nhận dữ liệu từ Server một cách bất đồng bộ mà không ảnh hưởng đến hiển thị và hoạt động của trang đang tồn tại.
                    </p>
                </div>
            </div>

            <div class="app_footer_line"></div>
            <div class="row">
                <div class="col-md-3">
                    <img src="../img/Technologies/bootstrap-logo.png" style="margin-left: 60px" alt="Bootstrap"
                         width="100px"/>
                </div>
                <div class="col-md-9">
                    <label style="font-size: 20px">Bootstrap</label>

                    <p>
                        Bootstrap là một front-end framework dùng để tạo ra website và ứng dụng web.
                        Bootstrap bao gồm các thiết kế HTML và CSS cơ bản như form, button, navigation,... và còn tích
                        hợp cả phần mở rộng với JavaSscript.
                        Bootstrap được viết bằng HTML, CSS, LESS, SASS, JavaScript và phát triển bởi Mark Otto và Jacob
                        Thornton tại Twitter.
                    </p>
                    Website: <a href="http://getbootstrap.com" target="_blank">getbootstrap.com</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="about_label">Công nghệ khác</div>
            <div class="app_space_line"></div>
            <div class="row">
                <div class="col-md-3">
                    <img src="../img/Technologies/angularjs-logo.png" alt="AngularJS" style="margin-top: 30px"
                         width="200px"/>
                </div>
                <div class="col-md-9">
                    <label style="font-size: 20px">AngularJS</label>

                    <p>
                        AngularJS là một open-source web application framework viết bằng ngôn ngữ JavaScript được bảo
                        trợ bởi Google và cộng đồng, hỗ trợ cho thiết kế ứng dụng đơn trang,
                        một trang ứng dụng web chỉ với HTML, CSS và Javascript tại phía Client-side.
                        Mục đích của AngularJS là làm tăng khả năng ứng dụng web với mô hình MVC, dễ dàng hơn cho việc
                        phát triển và kiểm thử.
                    </p>
                    Website: <a href="http://angularjs.org" target="_blank">angularjs.org</a>
                </div>
            </div>
        </div>
        <div class="app_footer_line"></div>
        <div class="row">
            <div class="col-md-3">
                <img src="../img/Technologies/HTML5_Logo_512.png" style="margin-left: 50px" alt="Bootstrap"
                     width="100px"/>
            </div>
            <div class="col-md-9">
                <label style="font-size: 20px">HTML5</label>

                <p>
                    HTML5 là một ngôn ngữ cấu trúc và trình bày nội dung cho World Wide Web và sẽ là công nghệ cốt lõi của Internet trong tương lai không xa, được đề xuất đầu tiên bởi Opera Software.
                    Đây là phiên bản thứ 5 của ngôn ngữ HTML - được tạo ra năm 1990 và chuẩn hóa như HTML4 năm 1997 - và xuất hiện vào tháng 12 năm 2012,
                    là 1 ứng viên được giới thiệu bởi World Wide Web Consortium (W3C).
                </p>
            </div>
        </div>

        <div class="row">
            <div class="about_label">Tham khảo</div>
            <div class="app_space_line"></div>
            <div class="row">
                <ul>
                    <li>
                        Bạn Nguyễn Thị Bích Thảo (1265028) - Nút "Xem thêm" ở trang Tìm kiếm.
                    </li>
                    <li>
                        Anh Nguyễn Trung Lợi (Swiss IT Bridge) - Hàm render trong func.js.
                    </li>
                    <li>
                        <a href="http://mobishop.com.vn" target="_blank">http://mobishop.com.vn</a> - Hình ảnh trong Slider và logo cho trang About.
                    </li>
                    <li>
                        <a href="http://www.mobileshop.com.eg/en/" target="_blank">http://www.mobileshop.com.eg/en/</a> - Layout cho trang Index và khung Tìm kiếm nâng cao.
                    </li>
                    <li>
                        <a href="http://www.mobishop.hk" target="_blank">http://www.mobishop.hk</a> - Thumbnail Sản phẩm mới nhất tại trang Index.
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>