<div class="jumbotron text-center app_standard center_screen app_jumbotron">
    <h1>Quản lý tài khoản người dùng</h1>
    <p>Thêm, xóa, sửa, liệt kê và tìm kiếm thông tin của <span class="text-danger">tài khoản người dùng</span>.</p>
</div>
<div ng-controller="accountController">
    <div class="row center_screen app_search_admin" style="margin-top: 30px">
        <div class="col-md-10">
            <form method="get" action="../page_manager_account.php">
                <div class="input-group">
                    <input type="text" class="form-control" name="keyword">
                    <div class="input-group-btn">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Tìm kiếm</button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-2">
        </div>
    </div>
    <table class="table center_screen" style="width: 95%">
        <thead>
        <tr>
            <th>ID</th>
            <th>Họ và tên</th>
            <th>Tên đăng nhập</th>
            <th>Phân quyền</th>
            <th>Thành phố</th>
            <th>Ngày sinh</th>
            <th>#</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $rowPerPage = 10;
        $pageNum = 1;
        $data = array();

        include 'Process/Model/AccountModel.php';

        if (isset($_GET['page'])) {
            $pageNum = $_GET['page'];
        }
        $offset = ($pageNum - 1) * $rowPerPage;

        if (isset($_GET['keyword'])) {
            $keyword = addslashes($_GET['keyword']);
            if (addslashes($_GET['keyword']) != ''){
                $data = AccountModel::getAccountsPerPageWithCondition($offset, $rowPerPage, 'username', $keyword, true);
            }
            else {
                $data = AccountModel::getAccountsPerPage($offset, $rowPerPage);
            }

        } else {
            $data = AccountModel::getAccountsPerPage($offset, $rowPerPage);
        }

        foreach ($data as $account) : ?>
            <tr>
                <form method="post" action="../page_edit_account.php">
                    <td><?php echo $account['id']; ?></td>
                    <td><?php echo $account['fullname']; ?></td>
                    <td><?php echo $account['account']; ?></td>
                    <td><?php echo $account['permission']; ?></td>
                    <td><?php echo $account['city']; ?></td>
                    <td><?php echo $account['birthday']; ?></td>
                    <td>
                        <span class="glyphicon glyphicon-remove remove-sign" title="Xóa"></span>
                        <input type="hidden" value="<?php echo $account['id'] ?>"/>
                        <input type="submit" value="Sửa" id="submit" name="submit"/>
                    </td>
                    <td class="hidden">
                        <input type="hidden" name="id" value="<?php echo $account['id'] ?>"/>
                        <input type="hidden" name="fullname" value="<?php echo $account['fullname'] ?>"/>
                        <input type="hidden" name="account" value="<?php echo $account['account'] ?>"/>
                        <input type="hidden" name="password" value="<?php echo $account['password'] ?>"/>
                        <input type="hidden" name="permission" value="<?php echo $account['permission'] ?>"/>
                        <input type="hidden" name="city" value="<?php echo $account['city'] ?>"/>
                        <input type="hidden" name="birthday" value="<?php echo $account['birthday'] ?>"/>
                    </td>
                </form>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <div class="center_screen center app_standard">
        <ul class="pagination">
            <?php
            if (isset($_GET['keyword']) && addslashes($_GET['keyword']) != '') {
                ?>
                <li id="previous-key"><a id="previous-sign-key" href="#">&lt;</a></li>
                <input type="text" class="hidden" id="previous-keyword"
                       value="<?php echo addslashes($_GET['keyword']) ?>"/>
            <?php
            } else {
                ?>
                <li id="previous"><a id="previous-sign" href="#">&lt;</a></li>
            <?php
            }

            $countRows = 0;

            if (isset($_GET['keyword']) && addslashes($_GET['keyword']) != '') {
                $countRows = AccountModel::countAccountsWithCondition(addslashes($_GET['keyword']));
            } else {
                $countRows = AccountModel::countAccounts();
            }

            $maxPage = ceil($countRows / $rowPerPage);

            $self = $_SERVER['PHP_SELF']; // link hien tai
            $nav = '';
            ?>

            <input type="hidden" id="currentPage" value="<?php echo $pageNum ?>"/>
            <input type="hidden" id="maxPage" value="<?php echo $maxPage ?>"/>

            <?php
            for($page = 1; $page <= $maxPage; ++$page)
            {
                if ($page == $pageNum)
                {
                    echo "<li class='active'><a href='#'>" . $page . "</a></li>";
                }
                else
                {
                    echo "<li><a href='" . $self . "?page=" . $page . "'>" . $page . "</a></li>";
                }
            }

            if (isset($_GET['keyword']) && addslashes($_GET['keyword']) != '') {
            ?>
            <li id="next-key"><a id="next-sign-key" href="#">&gt;</a></li>
            <input type="text" class="hidden" id="next-keyword" value="<?php echo addslashes($_GET['keyword']) ?>"/>
            <?php
            } else {
                ?>
                <li id="next"><a id="next-sign" href="#">&gt;</a></li>
            <?php
            }
            ?>
        </ul>
    </div>
</div>