<div class="app_standard center_screen">
    <div class="row" style="margin: 10px 0px 10px 0px">
        <button type="button" class="btn btn-danger right" data-toggle="collapse" data-target="#advanceSearch">
            Tìm kiếm nâng cao
        </button>
    </div>

    <div class="panel-group collapse" id="advanceSearch">
        <div class="panel panel-default">
            <div id="collapseOne" class="panel-collapse collapse in">
                <div class="panel-body">
                    <?php include 'view/Sub/search_advance.phtml' ?>
                </div>
            </div>
        </div>
    </div>

    <div class="app_footer_line"></div>
    <div class="row">
        <div class="col-md-3">
            <?php include '/Sub/app_user_navigator.phtml' ?>
        </div>
        <?php
        if (isset($_GET['ID'])) {
            $id = addslashes($_GET['ID']);
            DataProvider::ExecuteQuery("update mobile set View = View + 1 where ID = '$id'");
            $row = MobileModel::getMobileById($id);

            if ($row != false) {
            ?>
            <div class="col-md-9 app_top">
                <div class="col-md-6">
                    <img src="../img/Mobile/<?php echo $row['image'] ?>" class="app_thumbnail_detail" alt="Test"/>
                </div>
                <div class="col-md-6">
                    <div class="caption">
                        <h3><?php echo $row['name'] ?></h3>

                        <p>
                            Hãng: <?php echo $row['company'] ?><br/>
                            Xuất xứ: <?php echo $row['source'] ?><br/>
                            Giá: <?php echo number_format($row['price']) . ' VND' ?>
                        </p>
                        <input type="hidden" id="mobile-id" value="<?php echo $row['id'] ?>"/>
                        <?php
                        if (isset($_SESSION['user'])) {
                            echo '<button class="btn btn-success" role="button" id="add-cart">Thêm vào giỏ hàng</button>';
                        }
                        ?>
                    </div>
                </div>
                <div class="col-md-12" style="margin-top: 20px">
                    <span class="btn btn-primary active app_none_click">Số lượt xem <span
                            class="badge"><?php echo $row['view'] ?></span></span>
                    <span class="btn btn-primary active app_none_click">Số lượng bán <span
                            class="badge"><?php echo $row['sale'] ?></span></span>
                </div>
                <div class="col-md-12 caption app_mobile_description">
                    <h3>Đặc tả kỹ thuật</h3>

                    <p>
                        <?php echo $row['description'] ?>
                    </p>
                </div>
                <div class="col-md-12 caption">
                    <h3>Điện thoại cùng loại</h3>

                    <div class="row">
                        <?php
                        $count = 0;
                        foreach (MobileModel::getMobileByType($row['type']) as $mobile) {
                            if ($count == 6) {
                                break;
                            }
                            if ($count == 3) {
                                echo '</div>';
                                echo '<div class="row">';
                            }

                            if ($mobile['id'] != $id) {
                                ?>
                                <div class="col-md-4 thumbnail">
                                    <div class="col-md-4">
                                        <a href="../page_detail_product.php?ID=<?php echo $mobile['id'] ?>">
                                            <img src="../img/Mobile/<?php echo $mobile['image'] ?>"
                                                 alt="<?php echo $mobile['name'] ?>">
                                        </a>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="row">
                                            <label><?php echo $mobile['name'] ?></label>
                                        </div>
                                        <div class="row">
                                            Giá: <?php echo number_format($mobile['price']) . ' VND' ?>
                                        </div>
                                    </div>
                                </div>
                                <?php
                                ++$count;
                            }
                        }
                        if ($count != 3) {
                            echo '</div>';
                        }
                        ?>
                    </div>
                </div>
            <?php
                }
            }
            else {
            ?>
                <div class="col-md-9 app_top">
                    <div class="alert alert-danger">
                        <strong>Cảnh báo!</strong><br/>
                        Bạn vui lòng chọn sản phẩm để xem chi tiết.
                    </div>
                </div>
            <?php
            }
            ?>
        </div>
    </div>
</div>