<div class="row app_standard center_screen" style="margin-top: 30px">
    <div class="row">
        <label class="search_tag" style="font-size: 48px; color: #14a7c6">110001NP Team</label>
    </div>
    <div id="developers">
    </div>
</div>

<div class="template hidden" id="DeveloperLeftTemplate">
    <div class="row developers_border_left">
        <div class="col-md-4">
            <img class="img-circle developers_avatar_left" src="../img/avatar/{ image }.jpg" alt="{ name }" />
        </div>
        <div class="col-md-8">
            <div class="developers_circle"></div>
            <div class="page-header">
                <h3>{name} <br/><small>{ ID }</small></h3>
            </div>
        </div>
    </div>
</div>

<div class="template hidden" id="DeveloperRightTemplate">
    <div class="row developers_border_right">
        <div class="col-md-4">
            <img class="img-circle developers_avatar_left" src="../img/avatar/{ image }.jpg" alt="{ name }" />
        </div>
        <div class="col-md-8">
            <div class="developers_circle"></div>
            <div class="page-header">
                <h3>{ name } <br/><small>{ ID }</small></h3>
            </div>
        </div>
    </div>
</div>