<div class="widget">
        <?php
        if (isset($_SESSION['permission'])) {
            echo '<a href="../page_cart.php" style="text-decoration: none; color: #ffffff"  title="Giỏ hàng" class="glyphicon glyphicon-shopping-cart app_shopping_cart"></a>';
        }
        else {
            echo '<a href="../page_login.php" style="text-decoration: none; color: #ffffff" title="Đăng nhập" class="glyphicon glyphicon-log-in app_user"></a>';
        }
        ?>
        <span class="glyphicon glyphicon-arrow-up app_arrow_top" title="Trở về đầu trang"></span>
    <div class="left">
        <img src="../img/feedback.png" class="widget_feedback" alt="Give Feedback" />
    </div>
    <div class="left">
        <img src="../img/arrow.jpg" class="widget_status"/>
        <input type="text" disabled value="<?php echo $_SESSION['title'] ?>" class="widget_status_content"/>
    </div>
</div>