<div>
    <label>
        <?php
        $user = addslashes($_SESSION['user']);
        echo $user;
        ?>
    </label>
    <a href="#" data-toggle="modal" data-target="#smallModal" style="text-decoration: none" class="glyphicon glyphicon-log-out"></a>

</div>

<div class="modal fade" id="smallModal" tabindex="-1" role="dialog" aria-labelledby="smallModal" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Xác nhận</h4>
            </div>
            <div class="modal-body">
                Bạn đồng ý thoát chứ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" style="z-index: 10" data-dismiss="modal">Hủy</button>
                <a href="../../Process/LogoutController.php"><button type="button" class="btn btn-primary">Đồng ý</button></a>
            </div>
        </div>
    </div>
</div>