<div class="app_standard center_screen app_footer_line"></div>
<footer>
    <div class="app_standard center_screen">
        <div class="col-md-4">
            <ul>
                <li style="display: inline; margin: 0 5px;">
                    <img src="../../img/avatar/Nguyen_Thanh_Nhan.jpg" alt="Nguyễn Thành Nhân" title="Nguyễn Thành Nhân" class="img-rounded image_footer"/>
                </li>
                <li style="display: inline; margin: 0 5px;">
                    <img src="../../img/avatar/Vo_Hoai_Nam.jpg" alt="Võ Hoài Nam" title="Võ Hoài Nam" class="img-rounded image_footer"/>
                </li>
                <li style="display: inline; margin: 0 5px;">
                    <img src="../../img/avatar/Nguyen_Thi_Thuy_Ngan.jpg" alt="Nguyễn Thị Thủy Ngân" title="Nguyễn Thị Thủy Ngân" class="img-rounded image_footer"/>
                </li>
                <li style="display: inline; margin: 0 5px;">
                    <img src="../../img/avatar/Huynh_Chi_Phong.jpg" alt="Huỳnh Chí Phong" title="Huỳnh Chí Phong" class="img-rounded image_footer"/>
                </li>
            </ul>
        </div>
        <div class="col-md-8">
            <ul style="display: inline; list-style: none;">
                <li class="left">
                    MobiShop © 2014 - 110001NP<br>
                    <i>University of Science Ho Chi Minh City - Vietnam National University</i>
                </li>
                <li class="right" style="margin-left: 20px">
                    <a href="../../page_developers.php" style="text-decoration: none; color: #808080">Developers</a>
                </li>
                <li class="right">
                    <a href="../../page_about.php" style="text-decoration: none; color: #808080">About</a>
                </li>
            </ul>
        </div>
    </div>
</footer>