<ul class="nav nav-pills nav-stacked">
    <li><a href="page_search.php?act=price&keyword=priceLevel1">200.000 - 1.000.000</a></li>
    <li><a href="page_search.php?act=price&keyword=priceLevel2">1.000.000 - 5.000.000</a></li>
    <li><a href="page_search.php?act=price&keyword=priceLevel3">5.000.000 - 10.000.000</a></li>
    <li><a href="page_search.php?act=price&keyword=priceLevel4">10.000.000 - 20.000.000</a></li>
    <li><a href="page_search.php?act=price&keyword=priceLevel5">Hơn 20 triệu</a></li>
</ul>